services:
  db:
    image: postgres:16-alpine
    container_name: phoneme-activity-builder-db
    environment:
      POSTGRES_USER: phoneme-activity-builder
      POSTGRES_PASSWORD: cse3cwa
      POSTGRES_DB: phoneme-activity-builder
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U phoneme-activity-builder -d phoneme-activity-builder",
        ]
      interval: 5s
      timeout: 5s
      retries: 5

  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs-app
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production
      - HOSTNAME=0.0.0.0
      - PORT=3000
      - DATABASE_URL=postgresql://phoneme-activity-builder:cse3cwa@db:5432/phoneme-activity-builder
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  pgdata:
